name: Code Validation

on: 
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate HTML
        run: |
          npm install -g html-validator-cli
          for file in $(find . -name "*.html"); do
            html-validator --file="$file"
          done
        
      - name: Validate CSS
        run: |
          npm install -g css-validator
          for file in $(find . -name "*.css"); do
            css-validator "$file"
          done
        
      - name: Validate JavaScript
        run: |
          npm install -g eslint
          eslint "**/*.js"
          
      - name: Validate JSON
        run: |
          npm install -g jsonlint
          for file in $(find . -name "*.json"); do
            jsonlint "$file"
          done
