name: Code Validation

on: 
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate HTML
        run: |
          npm install -g html-validator-cli
          html-validator --file=index.html
        
      - name: Validate CSS
        run: |
          npm install -g css-validator
          css-validator styles.css
        
      - name: Validate JavaScript
        run: |
          npm install -g eslint
          eslint "**/*.js"
          
      - name: Validate JSON
        run: |
          npm install -g jsonlint
          jsonlint data.json
